# .github/workflows/multi-job-demo.yml
name: Multi-Job Demonstration

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build step
        run: echo "Building the application..."

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Running tests..."

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "Deploying to staging..."
